### PR TITLE
Delay options can now have zero values

### LINKED ISSUE #13: Command line should accept 0 values for delays
**Repro**

```bash
❯ clj -M:membrane.term screenshot --play script.sh --height 58 --width 133 --line-delay 0                                                                                   
*
* Error: --line-delay: expected positive integer
*
```

A `--line-delay` and/or `--final-delay` of `0` should be allowed.

### PR DESCRIPTION
**Pull request by lread**
Also introduced line continuation for usage help for readability.

Closes #13

### CODE REVIEW

File: src/com/phronemophobic/membrane/term/main.clj [hunk 1]
```diff
@@ -28,14 +29,15 @@ Replace membrane.term with your appropriate Clojure tools CLI launch sequence. F
...
 
-(defn- parse-pos-int [v]
-  (let [num (if (integer? v)
-                 v
-                 (when (and (string? v) (re-matches #"\d+" v))
-                   (Integer/parseInt v)))]
-    (if (and num (> num 0))
-      num
-      {:error "expected positive integer"})))
+(defn- parse-pos-int [min]
```
Comment (phronmophobic) [inline src/com/phronemophobic/membrane/term/main.clj:32]: Trying to think of a good name for this function now that it returns a parser and can accept non positive numbers depending on the input.

Comment (lread) [reply src/com/phronemophobic/membrane/term/main.clj:32]: Ah, interesting point. Maybe `pos-int-parser`?
Or `pos-int-parser-validator`?

Comment (phronmophobic) [reply src/com/phronemophobic/membrane/term/main.clj:32]: `pos?` is > 0 and it would be totally possible to pass a min that's less than 0. Is there a name that doesn't have `pos` in it? Maybe just `int-parser-validator`?

Comment (lread) [reply src/com/phronemophobic/membrane/term/main.clj:32]: Oh... right! `int-parser-validator` works for me!
